name: Build

on:
  workflow_call:
    inputs:
      PICO_BOARD:
        type: string
      LOG_ON_GP01:
        type: boolean
      BOOTSEL_BUTTON:
        type: boolean
  workflow_dispatch:
    inputs:
      PICO_BOARD:
        type: string
      LOG_ON_GP01:
        type: boolean
      BOOTSEL_BUTTON:
        type: boolean

env:
  FW_NAME: picoports__PICO_BOARD=${{ inputs.PICO_BOARD }}__LOG_ON_GP01=${{ inputs.LOG_ON_GP01 }}__BOOTSEL_BUTTON=${{ inputs.BOOTSEL_BUTTON }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '14.2.Rel1'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Selectively clone submodules
      run: |
        git submodule update --init -- pico-sdk debugprobe
        git -C pico-sdk submodule update --init -- lib/tinyusb
        git -C debugprobe submodule update --init -- freertos
        if [ ${{ inputs.PICO_BOARD }} == pico2 ]; then
          git -C debugprobe/freertos submodule update --init -- portable/ThirdParty/Community-Supported-Ports
        fi

    - name: Build
      run: |
        cmake -B build -DPICO_BOARD=${{ inputs.PICO_BOARD }} -DLOG_ON_GP01=${{ inputs.LOG_ON_GP01 }} -DBOOTSEL_BUTTON=${{ inputs.BOOTSEL_BUTTON }}
        make -C build -j $(nproc)
        mv -n build/picoports.uf2 build/${{ env.FW_NAME }}.uf2 || true

    - name: Store Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FW_NAME }}
        path: build/picoports*.uf2
