name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        PICO_BOARD: ["pico", "pico2"]
        LOG_ON_GP01: [false, true]
        BOOTSEL_BUTTON: [false, true]
    uses: ./.github/workflows/build.yml
    with:
      PICO_BOARD: ${{ matrix.PICO_BOARD }}
      LOG_ON_GP01: ${{ matrix.LOG_ON_GP01 }}
      BOOTSEL_BUTTON: ${{ matrix.BOOTSEL_BUTTON }}
