name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        PICO_BOARD: ["pico", "pico2"]
    uses: ./.github/workflows/build.yml
    with:
      PICO_BOARD: ${{ matrix.PICO_BOARD }}
      LOG_ON_GP01: false
      BOOTSEL_BUTTON: false

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Normalize firmware names
        run: |
          ls -l artifacts/
          mv \
            artifacts/picoports__PICO_BOARD=pico__*.uf2 \
            artifacts/picoports_pico_${{ github.ref_name }}.uf2
          mv \
            artifacts/picoports__PICO_BOARD=pico2__*.uf2 \
            artifacts/picoports_pico2_${{ github.ref_name }}.uf2
          ls -l artifacts/

      - name: Create Release
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          body: |
            See:

            - [Installation](https://github.com/sevenlab-de/picoports/blob/${{github.ref_name}}/README.md#installation)
            - [Usage](https://github.com/sevenlab-de/picoports/blob/${{github.ref_name}}/README.md#usage)
            - [Pinout](https://github.com/sevenlab-de/picoports/blob/${{github.ref_name}}/README.md#pinout)

            Variants:

            - `picoports_pico_${{ github.ref_name }}.uf2` is for Raspberry Pi Pico (based on RP2040 chip, marked as `RP2-B*`)
            - `picoports_pico2_${{ github.ref_name }}.uf2` is for Raspberry Pi Pico 2 (based on RP2350 chip, marked as `RP2350*`)
          fail_on_unmatched_files: true
          files: artifacts/picoports_pico*.uf2
